Specify "esnext" as TS lib
To avoid conflict with `console` type.

```
$ yarn run tsc
yarn run v1.22.4
$ /Users/tricknotes/src/github.com/tricknotes/FirebaseAuthenticationGoogleAppsScript/node_modules/.bin/tsc
node_modules/@types/google-apps-script/google-apps-script.base.d.ts:512:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'console' must be of type 'Console', but here has type 'console'.

512 declare var console: GoogleAppsScript.Base.console;
                ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:18958:13
    18958 declare var console: Console;
                      ~~~~~~~
    'console' was also declared here.

Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```